// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHBryoXxG6veK0Ra_SKOqiPtN5mMQikJQ',
    appId: '1:1039641452575:web:96b500dfd8b96690a3752a',
    messagingSenderId: '1039641452575',
    projectId: 'crudtutorial-76774',
    authDomain: 'crudtutorial-76774.firebaseapp.com',
    storageBucket: 'crudtutorial-76774.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiv6ETqLP3zlHO_DA2Iz_gfbBz07zbj9Q',
    appId: '1:1039641452575:android:156ff1556e880119a3752a',
    messagingSenderId: '1039641452575',
    projectId: 'crudtutorial-76774',
    storageBucket: 'crudtutorial-76774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVDsydvct4_rgc5r8jCosSKf8CTExRlCY',
    appId: '1:1039641452575:ios:f547d571233c8ddca3752a',
    messagingSenderId: '1039641452575',
    projectId: 'crudtutorial-76774',
    storageBucket: 'crudtutorial-76774.firebasestorage.app',
    iosBundleId: 'com.example.onlineDbMk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVDsydvct4_rgc5r8jCosSKf8CTExRlCY',
    appId: '1:1039641452575:ios:f547d571233c8ddca3752a',
    messagingSenderId: '1039641452575',
    projectId: 'crudtutorial-76774',
    storageBucket: 'crudtutorial-76774.firebasestorage.app',
    iosBundleId: 'com.example.onlineDbMk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHBryoXxG6veK0Ra_SKOqiPtN5mMQikJQ',
    appId: '1:1039641452575:web:bf83631addbfa195a3752a',
    messagingSenderId: '1039641452575',
    projectId: 'crudtutorial-76774',
    authDomain: 'crudtutorial-76774.firebaseapp.com',
    storageBucket: 'crudtutorial-76774.firebasestorage.app',
  );
}
